#### 写出导入numpy的语句，并且给numpy别名为np。

In [7]:
import numpy as np

#### 创建一个变量名为`arr1`的一维数组，里面的元素为整数6、2、-7、2、8、-2、1。

In [11]:
arr1=np.array([6,2,-7,2,8,-2,1])
arr1

array([ 6,  2, -7,  2,  8, -2,  1])

#### 创建一个变量名为`arr2`的二维数组，里面的元素为以下两个数组：由整数1、3、5组成的一维数组，以及由整数2、4、6组成的一维数组。

In [12]:
arr2=np.array([[1,3,5],[2,4,6]])
arr2

array([[1, 3, 5],
       [2, 4, 6]])

#### 分别打印`arr1`和`arr2`的维度、形状、元素数量、元素类型。

In [13]:
print(arr1.ndim)
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

1
(7,)
7
int32


#### 创建一个变量名为`arr_all_0`的一维数组，里面的元素为6个0。

In [15]:
arr_all_0= np.zeros(6)
arr_all_0

array([0., 0., 0., 0., 0., 0.])

#### 创建一个变量名为`arr_all_1`的一维数组，里面的元素为6个1。

In [16]:
arr_all_1=np.ones(6)
arr_all_1

array([1., 1., 1., 1., 1., 1.])

#### 创建一个变量名为`arr_even`的一维数组，里面的元素为10（包括10）到20（包括20）之间的偶数。

In [18]:
arr_even=np.arange(10,21,2)
arr_even

array([10, 12, 14, 16, 18, 20])

In [19]:
# 在一维数组添加新的元素 concatenate 函数接收的参数可以是列表
import numpy as np
arr1=np.array([5,17,3,25])
arr2=np.zeros(2)
arr3=np.ones(3)
np.concatenate([arr1,arr2,arr3])


array([ 5., 17.,  3., 25.,  0.,  0.,  1.,  1.,  1.])

In [20]:
# python列表sorted 调用后返回排序好的列表不改变原有的列表 sort函数什么都不返回，但原始列表会被排序好
# numpy 里面两种sort方法 sort(arr1)不改变arr1 arr1.sort()什么都不返回
import numpy as np
arr1=np.array([5,17,3,25])
print(np.sort(arr1)) 
print(arr1)

[ 3  5 17 25]
[ 5 17  3 25]


In [21]:
import numpy as np
arr1=np.array([5,17,3,25])
print(arr1.sort()) 
print(arr1)

None
[ 3  5 17 25]


In [26]:
# 通过索引获取元素正向01234 倒着 最后一个元素-1 -2 -3
arr1[1:2]

array([5])

In [29]:
# 数组和数字进行运算
arr1.max()

arr1.min()
arr1.sum()
arr1.mean()

12.5

In [33]:
# numpy 广播机制根据条件筛选数组元素
import numpy as np

arr2 = np.array([-22, 3, 65, 9, 11, 7])
filtered_arr = arr2[arr2 > 6]
filtered_arr1=arr2[(arr2>6)&(arr2<10)]
print(filtered_arr)
print(filtered_arr1)

[65  9 11  7]
[9 7]
