In [1]:
import numpy as np

In [2]:
# 创建一维数组
arr1 = np.array([1,2,2])
arr1

array([1, 2, 2])

In [6]:
# 创建二维数组
arr2 = np.array([[1,2,3],[4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
# 返回数组维度 ndim
arr3 = np.array([[[1,2,3],[4,5,6],[5,6,7]]])
arr3
# print(arr3.ndim)

array([[[1, 2, 3],
        [4, 5, 6],
        [5, 6, 7]]])

In [12]:
# shape 会返回一个元组表示各个维度的元素的个数
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(3,)
(2, 3)
(1, 3, 3)


In [15]:
"""最外层：arr3 是一个包含一个元素的列表（即一个大括号 [] 包裹的内容）。这个元素是一个二维数组。
因此，最外层的大小是 1。
中间层：这个二维数组包含 3 个子数组（[1, 2, 3], [4, 5, 6], [5, 6, 7]）。
因此，中间层的大小是 3。
最内层：每个子数组包含 3 个元素。
因此，最内层的大小是 3。
综合起来，arr3 的形状是 (1, 3, 3)，表示：
最外层有 1 个元素（一个二维数组）。
这个二维数组有 3 行。
每行有 3 个元素。"""

'最外层：arr3 是一个包含一个元素的列表（即一个大括号 [] 包裹的内容）。这个元素是一个二维数组。\n因此，最外层的大小是 1。\n中间层：这个二维数组包含 3 个子数组（[1, 2, 3], [4, 5, 6], [5, 6, 7]）。\n因此，中间层的大小是 3。\n最内层：每个子数组包含 3 个元素。\n因此，最内层的大小是 3。\n综合起来，arr3 的形状是 (1, 3, 3)，表示：\n最外层有 1 个元素（一个二维数组）。\n这个二维数组有 3 行。\n每行有 3 个元素。'

In [16]:
# size会返回给我们数组里面元素的总个数
print(arr1.size)
print(arr2.size)
print(arr3.size)

3
6
9


In [18]:
# dtype会返回给我们数组元素的类型
print(arr1.dtype)
print(arr2.dtype)

int32
int32


In [26]:
# zeros创建元素全部为0的数组
np.zeros(3)
# ones返回全部为1
np.ones(5)
zeros_2d = np.zeros((2, 3))
print("2D zeros array:")
print(zeros_2d)

2D zeros array:
[[0. 0. 0.]
 [0. 0. 0.]]


In [24]:
# arange表示针对的是arr里面的方法
np.arange(5,10,2)
# 5起始值，10结束值，2步长 结束值不在范围内

array([5, 7, 9])